# Generated by Django 4.1.4 on 2022-12-24 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110, verbose_name='GENERIC NAME')),
                ('name2', models.CharField(blank=True, max_length=60, null=True, verbose_name='BRAND NAME')),
                ('availability', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('dicount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('rating', models.IntegerField(default=2)),
                ('description', models.TextField(blank=True, null=True, verbose_name='DRUG DESCRIPTION')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110, verbose_name='DRUG CATEGORY')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=2)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfe.item')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=14, verbose_name='ORDER CODE')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfe.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='product/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfe.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.CharField(help_text='Generally Consumed With Water', max_length=100, verbose_name='DRUG HIGHLIGHT')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfe.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfe.itemcategory'),
        ),
    ]
