# Generated by Django 4.1.4 on 2022-12-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfe', '0003_item_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pic',
            field=models.ImageField(default='null.jpg', upload_to='product/'),
            preserve_default=False,
        ),
    ]
