# Generated by Django 4.1.4 on 2022-12-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfe', '0004_alter_item_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='image',
            field=models.ImageField(default='null.jpg', upload_to='category/'),
            preserve_default=False,
        ),
    ]
