# Generated by Django 4.1.4 on 2022-12-25 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfe', '0005_itemcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemhighlights',
            name='highlight',
            field=models.CharField(help_text='Generally Consumed With Water', max_length=20, verbose_name='DRUG HIGHLIGHT'),
        ),
        migrations.AlterField(
            model_name='itemhighlights',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_highlight', to='cfe.item'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_pic', to='cfe.item'),
        ),
    ]
