# Generated by Django 4.1.4 on 2022-12-25 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfe', '0007_itemdeliverylocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30, verbose_name='Delivery Location')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='address',
            field=models.CharField(default='Juja', max_length=30, verbose_name='Delivery Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_category', to='cfe.itemcategory'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='DRUG CATEGORY'),
        ),
        migrations.DeleteModel(
            name='ItemDeliveryLocation',
        ),
    ]
