# Generated by Django 4.1.4 on 2022-12-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfe', '0008_deliverylocation_orderitem_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryLocation',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
