# Generated by Django 4.1.4 on 2022-12-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfe', '0009_delete_deliverylocation_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=110, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=110, unique=True, verbose_name='GENERIC NAME'),
        ),
    ]
