# Generated by Django 4.1.4 on 2022-12-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_clientpurchase_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpurchase',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
    ]
